steps:
  - name: build-and-push
    image: docker:dind
    privileged: true
    when:
      event: [push, manual]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASSWORD:
        from_secret: registry_password
    commands:
      - docker login registry.gtech01.de -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker build --build-arg BUILD_HASH=${CI_COMMIT_SHA} -t registry.gtech01.de/folio:latest .
      - docker push registry.gtech01.de/folio:latest

  - name: deploy
    image: alpine
    when:
      event: [push, manual]
    environment:
      CLOUDRON_TOKEN:
        from_secret: cloudron_token
    commands:
      - apk add --no-cache curl
      - curl -s -H "Authorization:Bearer $CLOUDRON_TOKEN" https://my.gtech01.de/api/v1/apps