steps:
  - name: build-and-push
    image: docker:dind
    privileged: true
    when:
      event: [push, manual]
    environment:
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASSWORD:
        from_secret: registry_password
    commands:
      - docker login registry.gtech01.de -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - docker build -t registry.gtech01.de/folio:latest .
      - docker push registry.gtech01.de/folio:latest